///
/// @Generated by Mockolo
///


@testable import ios_training_fujii

class WeatherModelMock: WeatherModel {
    init() { }

    private(set) var fetchWeatherAPICallCount = 0
    var fetchWeatherAPIHandler: ((String) throws -> (WeatherDataModel))?
    func fetchWeatherAPI(area: String) throws -> WeatherDataModel {
        fetchWeatherAPICallCount += 1
        if let fetchWeatherAPIHandler = fetchWeatherAPIHandler {
            return try fetchWeatherAPIHandler(area)
        }
        fatalError("fetchWeatherAPIHandler returns can't have a default value thus its handler must be set")
    }
}

